plugins {
    id 'java'
    id "com.gradleup.shadow" version "8.3.5"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group 'cz.raixo.mobs'
version '1.0.0'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://jitpack.io' }
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
    maven { url = "https://repo.codemc.io/repository/maven-public/" }
    maven { url = "https://repo.aikar.co/content/groups/aikar/" }
    maven { url = "https://repo.minebench.de/" }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    compileOnly project(':MineBlocks')

    compileOnly 'net.kyori:adventure-platform-bukkit:4.2.0'
    compileOnly "co.aikar:acf-bukkit:0.5.1-SNAPSHOT"
    compileOnly 'de.themoep:minedown-adventure:1.7.1-SNAPSHOT'
}

shadowJar {
    archiveFileName = "MineMobs-${project.version}.jar"
    relocate 'co.aikar.commands', 'cz.raixo.blocks.libs.acf'
    relocate 'co.aikar.locales', 'cz.raixo.blocks.libs.acf.locales'
    relocate 'de.themoep.minedown', 'cz.raixo.blocks.libs.minedown'
    relocate 'net.kyori.adventure', 'cz.raixo.blocks.libs.adventure'
    relocate 'net.kyori.examination', 'cz.raixo.blocks.libs.adventure.examination'

    dependencies {
        exclude(project(':MineBlocks'))
    }
}
